# Generated by Django 3.2.13 on 2023-10-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_customer_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtimes',
            old_name='time',
            new_name='showtime',
        ),
    ]
